---
apiVersion: v1
kind: Service
metadata:
  name: demo-querier
  namespace: demo
  labels:
    app: demo-querier
spec:
  selector:
    app: demo-querier
  ports:
    - port: 8080
      protocol: TCP
      name: client
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-querier
  namespace: demo
spec:
  serviceName: demo-querier
  replicas: 1
  selector:
    matchLabels:
      app: demo-querier
  template:
    metadata:
      labels:
        app: demo-querier
    spec:
      containers:
        - name: querier
          image: kamolhasan/prom-query:alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
          args:
            - "-n=10"
            - "-p=true"
            - "-username=****"
            - "-password=****"
            - "-license=*****"
            - "-url=https://appscode.ninja/searchlight/query/"
          ports:
            - containerPort: 8080
